[workspace]
path = "backend"

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
installArgs = ["--legacy-peer-deps"]
cmds = ["cd backend && npm install --include=dev"]

[phases.build]
cmds = ["cd backend && npx tsc"]

[start]
cmd = "cd backend && npm start"
